import React, { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { toast } from "@/hooks/use-toast";
import { supabase } from "@/lib/supabase";
import { fetchUserTicketForGroup, Ticket as TicketType } from "@/lib/tickets";
import Ticket from "./Ticket";
import { Banknote, ShieldCheck, CreditCard, Landmark, Check, Loader2 } from "lucide-react";

interface CheckoutModalProps {
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
  groupId: string;
  origin: string;
  destination: string;
  pricePerSeat: number;
  passengerName: string;
  onCheckoutSuccess?: () => void;
}

type CheckoutStep = "confirm" | "paying" | "ticket";

const CheckoutModal: React.FC<CheckoutModalProps> = ({
  isOpen,
  onOpenChange,
  groupId,
  origin,
  destination,
  pricePerSeat,
  passengerName,
  onCheckoutSuccess,
}) => {
  const [step, setStep] = useState<CheckoutStep>("confirm");
  const [paymentMethod, setPaymentMethod] = useState<"card" | "transfer" | "driver">("card");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [generatedTicket, setGeneratedTicket] = useState<TicketType | null>(null);

  const handlePay = async () => {
    setIsSubmitting(true);
    setStep("paying");

    try {
      // 1. Simulate payment gateway delay (e.g. 2s)
      await new Promise((resolve) => setTimeout(resolve, 2000));

      if (!supabase) {
        throw new Error("Supabase is not configured.");
      }

      // 2. Complete order by updating the travel group status to closed
      const { error: updateError } = await supabase
        .from("travel_groups")
        .update({ status: "closed" })
        .eq("id", groupId);

      if (updateError) {
        throw new Error(updateError.message);
      }

      // 3. Fetch the newly created ticket generated by the database trigger
      // Retry a few times if the trigger takes a millisecond to complete
      let ticket: TicketType | null = null;
      for (let i = 0; i < 5; i++) {
        ticket = await fetchUserTicketForGroup(groupId);
        if (ticket) break;
        await new Promise((resolve) => setTimeout(resolve, 300));
      }

      if (!ticket) {
        throw new Error("Ticket was not generated in time. Please check your dashboard.");
      }

      setGeneratedTicket(ticket);
      setStep("ticket");
      
      toast({
        title: "Booking confirmed!",
        description: "Your seat has been reserved and your ticket is ready.",
      });

      if (onCheckoutSuccess) {
        onCheckoutSuccess();
      }
    } catch (error) {
      console.error("[checkout] Error booking order:", error);
      toast({
        title: "Checkout failed",
        description: error instanceof Error ? error.message : "Please try again.",
        variant: "destructive",
      });
      setStep("confirm");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md max-h-[90vh] overflow-y-auto no-scrollbar p-6">
        {step !== "ticket" && (
          <DialogHeader className="mb-4">
            <DialogTitle className="text-xl font-extrabold text-foreground flex items-center gap-2">
              <Banknote className="w-6 h-6 text-primary" />
              Secure Checkout
            </DialogTitle>
          </DialogHeader>
        )}

        {step === "confirm" && (
          <div className="space-y-6">
            {/* Route Summary */}
            <div className="bg-secondary/40 rounded-2xl p-5 border border-border">
              <span className="text-[10px] uppercase font-bold text-muted-foreground tracking-wider">Group Ride Route</span>
              <div className="flex items-center justify-between gap-4 mt-2 mb-4">
                <div className="flex-1 min-w-0">
                  <p className="font-extrabold text-foreground text-sm truncate">{origin}</p>
                </div>
                <div className="w-6 h-0.5 border-t border-dashed border-muted-foreground/45 shrink-0" />
                <div className="flex-1 min-w-0 text-right">
                  <p className="font-extrabold text-foreground text-sm truncate">{destination}</p>
                </div>
              </div>

              <div className="pt-3 border-t border-border/60 flex justify-between items-center text-sm font-semibold">
                <span className="text-muted-foreground">Price per seat</span>
                <span className="text-foreground text-base font-extrabold">₦{pricePerSeat}</span>
              </div>
            </div>

            {/* Payment Method Selector */}
            <div className="space-y-3">
              <label className="text-sm font-bold text-foreground">Select Payment Method</label>
              
              <div className="grid grid-cols-3 gap-3">
                <button
                  type="button"
                  onClick={() => setPaymentMethod("card")}
                  className={`flex flex-col items-center justify-center p-4 rounded-xl border text-center transition-all gap-2 ${
                    paymentMethod === "card"
                      ? "border-primary bg-primary/5 text-primary"
                      : "border-border bg-card text-muted-foreground hover:bg-secondary/50"
                  }`}
                >
                  <CreditCard className="w-5 h-5" />
                  <span className="text-xs font-bold">Pay with Card</span>
                </button>

                <button
                  type="button"
                  onClick={() => setPaymentMethod("transfer")}
                  className={`flex flex-col items-center justify-center p-4 rounded-xl border text-center transition-all gap-2 ${
                    paymentMethod === "transfer"
                      ? "border-primary bg-primary/5 text-primary"
                      : "border-border bg-card text-muted-foreground hover:bg-secondary/50"
                  }`}
                >
                  <Landmark className="w-5 h-5" />
                  <span className="text-xs font-bold">Bank Transfer</span>
                </button>

                <button
                  type="button"
                  onClick={() => setPaymentMethod("driver")}
                  className={`flex flex-col items-center justify-center p-4 rounded-xl border text-center transition-all gap-2 ${
                    paymentMethod === "driver"
                      ? "border-primary bg-primary/5 text-primary"
                      : "border-border bg-card text-muted-foreground hover:bg-secondary/50"
                  }`}
                >
                  <Landmark className="w-5 h-5" />
                  <span className="text-xs font-bold">Pay Driver</span>
                </button>
              </div>
            </div>

            <div className="flex items-center gap-2 bg-emerald-50 text-emerald-800 text-xs px-4 py-3 rounded-xl border border-emerald-100">
              <ShieldCheck className="w-5 h-5 text-emerald-600 shrink-0" />
              <span>Payments are processed securely. Your fare is protected until the trip ends.</span>
            </div>

            <Button
              onClick={handlePay}
              disabled={isSubmitting}
              className="w-full py-6 text-base font-extrabold"
            >
              Pay ₦{pricePerSeat}
            </Button>
          </div>
        )}

        {step === "paying" && (
          <div className="py-12 flex flex-col items-center justify-center text-center space-y-4">
            <Loader2 className="w-12 h-12 text-primary animate-spin" />
            <div>
              <h3 className="text-lg font-bold text-foreground">Processing Payment</h3>
              <p className="text-sm text-muted-foreground mt-1">Please do not refresh the page or click back.</p>
            </div>
          </div>
        )}

        {step === "ticket" && generatedTicket && (
          <div className="py-2">
            <DialogHeader className="mb-2 text-center">
              <DialogTitle className="text-2xl font-extrabold text-foreground">
                Booking Confirmed!
              </DialogTitle>
              <p className="text-sm text-muted-foreground">
                Your boarding pass has been created successfully.
              </p>
            </DialogHeader>
            <Ticket ticket={generatedTicket} passengerName={passengerName} />
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
};

export default CheckoutModal;
